server:
  port: 8080
  servlet:    context-path: /api/apps
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          url-expression: "'lb:http://'+serviceId"
          predicates:            - name: Path
              args:                pattern: "'${server.servlet.context-path}/'+serviceId+'/**'"
      routes:
        - id: route_01
          uri: lb:http://producer
          predicates:
            - name: Path
              args:
                patterns:
                  - ${server.servlet.context-path}/getfoo/**
                  - ${server.servlet.context-path}/actu-check/producer/**
          filters:
            - RewritePath=${server.servlet.context-path}/getfoo(?<remaining>.*), $\{remaining}/
            - RewritePath=${server.servlet.context-path}/actu-check/producer(?<remaining>.*), $\{remaining}/
            - AddRequestParameter=foo, bar
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: trace